### PR TITLE
Adds raise_for_status options to RetryClient

### PR DESCRIPTION
**Pull request by hashstat**
If raise_for_status is True, raise_for_status() will be called
automatically after receiving the final response.

### CODE REVIEW

**Comment by inyutin** [comment]
@hashstat Hi! Thank you for PR, but I definitely not sure if it is useful. Isn't ```raise_for_status``` should work as well? You can put as param to ```RetryClient``` or as param to get/.../delete request. It will be taken as corresponding aiohttp params. Also you can manipulate for which exceptions you want to retry by ```RetryOptions.exceptions```. So it should work. 

Am I miss something?

**Comment by hashstat** [comment]
Passing `raise_for_status` on to the underlying `ClientSession` will cause the exception to be raised on the first error rather than after retrying. This commit postpones calling `raise_for_status()` until after retrying and failing. In short, without this patch, passing `raise_for_status=True` will prevent any retries if there is an error. Unless `exceptions={aiohttp.ResponseError}` is also passed, but that kind of defeats the purpose of passing `raise_for_status=True`.

**Comment by inyutin** [comment]
@hashstat So, am I right that you want to raise exception but only if last try failed?

I don't like ```raise_for_status```, 'cause it overrides aiohttp variable name. What about ```raise_last_exception: bool = False``` ? If it is true last try would exception in case of failing. I suppose it can be implemented simply by adding ```raise_for_status=True``` on last try. 

Please, correct me, if I misunderstood your suggestion

**Comment by hashstat** [comment]
Currently, using `raise_for_status=True` breaks aiohtp-retry because aiohttp will raise an exception on first failure and not give aiohttp-retry a chance to retry, so the two are incompatible. This is even demonstrated in the readme.

The purpose of the `raise_for_status` argument is as a shortcut so one can do `session.get(..., raise_for_status=True)` instead of
```python
response = await session.get(..., raise_for_status=False)
response.raise_for_status()
```

The proposed change retains that same behavior but allows for retries. `retry_client.get(..., retry_options=options, raise_for_status=True)` would be the same as
```python
response = await retry_client.get(..., retry_options=options, raise_for_status=False)
response.raise_for_status()
```

Using `raise_last_exception=True` would provide a workaround, but if an unknowing user passes `raise_for_status=True`, they are still going to be surprised that the retry options they configured have no effect. I guess I'm just suggesting that `raise_for_status` should do what's expected and not break aiohttp-retry.

**Comment by inyutin** [comment]
@hashstat 
Thank you, I finally reimplemented your suggestion here:
https://github.com/inyutin/aiohttp_retry/pull/28

**Comment by inyutin** [comment]
Use v2.3.3

**Pull request closed without merging**
